/****** Object:  Table [dbo].[SquadPlayer]    Script Date: 7/29/2015 1:04:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SquadPlayer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Squad] [int] NOT NULL,
	[Player] [int] NOT NULL,
 CONSTRAINT [PK_SquadPlayer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

